### PR TITLE
OpenAPI 3 support

### PR DESCRIPTION
**Pull request by maksbotan**

### CODE REVIEW

**Comment by maksbotan** [comment]
Hi @fisx, @fizruk, @phadej, @Sir4ur0n, @roosemberth.

I've finished this PR. I've added `openapi3` dependency under a flag, disabled by default, to make `servant-swagger-ui` support both `swagger2` and `openapi3` packages, until the former is deprecated.

Do you have objections or other proposals?

I also hope for some preliminary testing before I make Hackage releases.

**Comment by Sir4ur0n** [comment]
> I've finished this PR. I've added openapi3 dependency under a flag, disabled by default, to make servant-swagger-ui support both swagger2 and openapi3 packages, until the former is deprecated.

Isn't it inconsistent with the duplication of `servant-swagger` and `swagger2`? I don't mind _per se_, but I find it weird for developers to have a clear separation between Open API 2 and Open API 3 for the Swagger + Servant integration but not for the UI 😅 

That being said, I will try to test this tomorrow on our (private, sorry) application and give you feedback!

Again, thank you for this work 🙇‍♂️

**Comment by maksbotan** [comment]
@Sir4ur0n hi! how is it going with the testing? :)

**Comment by roosemberth** [comment]
> Do you have objections or other proposals?

LGTM.

I don't have the time to thoroughly review this MR, but it _looks_ good and this is great! Thanks!

**Comment by fizruk** [comment]
> I've finished this PR. I've added `openapi3` dependency under a flag, disabled by default, to make `servant-swagger-ui` support both `swagger2` and `openapi3` packages, until the former is deprecated.
> 
> Do you have objections or other proposals?

@maksbotan Great work! I would advise to create a separate package for discoverability (`openapi3`, `servant-openapi3` and `servant-openapi3-ui` is a nice lineup) and ease of use (no flag tweaking for end users).

**Comment by maksbotan** [comment]
@fizruk I've actually found a way to make separate `servant-openapi-ui` without duplicating the actual UI files :)
Please take another look.

**Comment by maksbotan** [comment]
I've updated swagger-ui to 3.35.1 and removed git dependency on `openapi3` since that is now on Hackage.

I guess it's time to merge and release this package as well.

**Comment by Profpatsch** [comment]
`servant-swagger-ui-core` still depends on `swagger2`, is this intended?

**Comment by Profpatsch** [comment]
And 

```
"servant-openapi-ui" -> "servant-swagger-ui";
"servant-openapi-ui" -> "servant-swagger-ui-core";
```

meaning `servant-openapi-ui` has a transitive dependency on `swagger2`.

**Comment by Profpatsch** [comment]
Okay lol, stack building these two modules at the same time just made my machine OOM:

```
openapi3               > [ 5 of 17] Compiling Data.OpenApi.Internal
swagger2               > [ 2 of 17] Compiling Data.Swagger.Internal.AesonUtils
swagger2               > [ 3 of 17] Compiling Data.Swagger.Internal.TypeShape
swagger2               > [ 4 of 17] Compiling Data.Swagger.Internal.Utils
swagger2               > [ 5 of 17] Compiling Data.Swagger.Internal
```

**Comment by maksbotan** [comment]
I've updated this with my recent changes to master. Sadly I don't yet see a way to fix the "depends on both swager2 and openapi3" problem. `servant-swagger-ui` and `servant-openapi-ui` share the same `swagger-ui` (js) code and I don't want to duplicate that code in the both packages. Perhaps this can be split even further?

**Comment by Profpatsch** [comment]
> `servant-swagger-ui` and `servant-openapi-ui` share the same `swagger-ui` (js) code and I don't want to duplicate that code in the both packages.

I have not looked at the code in detail, but I don’t see a reason why a bit of duplication would be unreasonable if it gets rid of quite serious double depenencies.

**Comment by gsebil08** [comment]
Hello,
Thanks for the job done!
Do you have any news about this PR? I mean, will it be merged to master?

Thanks!

**Comment by maksbotan** [comment]
Hi @gsebil08! Thanks for the interest :)
I couldn't come up with a nice way to avoid duplication and was overwhelmed by other stuff lately. I will try to do in the non-creative way soon.

Anyway, I've been using the version from this PR for my work and it works well.

**Comment by gsebil08** [comment]
Hi @maksbotan! Thanks for your quick reply!
I used to work with @Sir4ur0n (😘), so we are also using the version from this PR and it works like a charm!

I was simply upgrading some of our dependencies in our project, and wondering about the status of this one 😄

**Comment by maksbotan** [comment]
Hi all! @Sir4ur0n @gsebil08 and especially @phadej, please review this once again.

I've found a nice (I think) way to generalize this to support both `swagger2` and `openapi3` without actually pulling both packages into deps. Namely, I've made all `serve*` functions accept arbitrary `ToJSON a => a` as input and serve plain `Value` in APIs. This way the package no longer depends even on `swagger2`.

Please tell me what you think.

I think I will go ahead with merging and Hackage release if there are no responses in a week.

**Comment by phadej** [comment]
@maksbotan I'm not participating in servant development, don't expect me to review.

**Comment by gsebil08** [comment]
Hello @maksbotan, thanks for the suggestion!
I don't feel legitimate to review the changes, but still I tried to used this on my project.
And I am facing a weird issue and I don't know how to bypass it.
On my first attempt, I tried to link to the latest commit of this PR in my stack.yaml file:
```yaml
resolver: lts-17.2
packages:
  - .
extra-deps:
  - git: git@github.com:maksbotan/servant-swagger-ui.git
    commit: 6576953c39bf1407813ba1880525ed08ea8af9eb
```
And got:
```shell script
Cloning 6576953c39bf1407813ba1880525ed08ea8af9eb from git@github.com:maksbotan/servant-swagger-ui.git
No cabal file found for Repo from git@github.com:maksbotan/servant-swagger-ui.git, commit 6576953c39bf1407813ba1880525ed08ea8af9eb
```
So I tried to add the `subdirs` section, as following:
```yaml
  - git: git@github.com:maksbotan/servant-swagger-ui.git
    commit: 6576953c39bf1407813ba1880525ed08ea8af9eb
    subdirs:
      - servant-swagger-ui
      - servant-openapi-ui
```
and finally face:
```shell script
Cloning 6576953c39bf1407813ba1880525ed08ea8af9eb from git@github.com:maksbotan/servant-swagger-ui.git
No cabal file found for Repo from git@github.com:maksbotan/servant-swagger-ui.git, commit 6576953c39bf1407813ba1880525ed08ea8af9eb in subdir servant-openapi-ui
```

I must have miss something which I can't find on my own... Do you have any idea?

**Comment by maksbotan** [comment]
Hi @gsebil08,

Use subdirs `servant-swagger-ui-core` and `servant-swagger-ui`. `servant-openapi-ui` is gone, no longer needed :)

**Comment by gsebil08** [comment]
Thanks for your answer. I was lost between the changes I must do and the changes @Sir4ur0n did in the first place.
Here are the changes I did on our project:

## package.yaml
```diff
- servant-openapi-ui
+ servant-swagger
+ servant-swagger-ui
```
## OpenApiServer
```diff
- import Servant.OpenAPI.UI (openapiSchemaUIServer)
+ import Servant.Swagger.UI (swaggerSchemaUIServer)
```
## stack.yaml
```diff
- commit: 09ee7a2325d37b0c733edd89b3264403c4d82ff9
-    subdirs:
-      - servant-openapi-ui
+commit: 6576953c39bf1407813ba1880525ed08ea8af9eb
+    subdirs:
+      - servant-swagger-ui
```

And in our `swagger-ui` the `oneOf` feature is still working great!!

If you really want, I can have a look on the changes you made on your pull request, but as I am a "simple user" I am not sure it will be useful...

**Comment by maksbotan** [comment]
Great it worked for you!

**Comment by Profpatsch** [comment]
> Namely, I've made all `serve*` functions accept arbitrary `ToJSON a => a` as input and serve plain `Value` in APIs. This way the package no longer depends even on `swagger2`.
> 
> Please tell me what you think.

Sound good!

**Pull request merged**
