### PR TITLE
Lift restriction of swagger spec delivery from Handler to any Monad

### PR DESCRIPTION
**Pull request by dmjio**
- By using the `ServerT` type family we allow custom monads to deliver swagger.json

### CODE REVIEW

**Comment by dmjio** [comment]
@phadej @fisx @arianvp 

Ran into an issue at work where we can't use custom monads when serving stuff with `servant-swagger-ui`, this patch fixes that, and is backwards compatible. 

Would love to upstream this with everybody's approval.

**Comment by dmjio** [comment]
Pulling in @fizruk as well

**Comment by dmjio** [comment]
@haskell-servant/maintainers. If nobody has any problems with this, I will just merge by end of day.

**Comment by fizruk** [comment]
Looks great, thank you! Sorry for late response 😅

**Pull request merged**
